apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-crud-deployment
spec:
  selector:
    matchLabels:
      app: springboot-k8s-mysql
  replicas: 3
  template:
    metadata:
      labels:
        app: springboot-k8s-mysql
    spec:
      containers:
        - name: springboot-crud-k8s
          image: teja0102/springboot-crud-k8s:latest
          ports:
            - containerPort: 8080

---

apiVersion: v1 
kind: Service 
metadata: 
  name: springboot-crud-svc
spec:
  selector:
    app: springboot-k8s-mysql
  ports:
    - port: 8080
  type: ClusterIP

---

apiVersion: v1
kind: Ingress
metadata:
  name: springboot-crud-svc
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
spec:
  rules:
  - host: springboot-crud-svc.3c17db-c62a41fe.hcp.centralindia.azmk8s.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service: 
            name: springboot-crud-svc
            port: 
              number: 8080
